### ISSUE TITLE
Cannot upgrade to Rails 6.0.1

### ISSUE THREAD

**Issue by rexmadden** [alecdotninja/active_record_distinct_on#10]
Running `bundle update` with Rails 6.0.1

Error
```
Bundler could not find compatible versions for gem "activerecord":
active_record_distinct_on (~> 0.1.6) was resolved to 0.1.6, which depends on
      activerecord (>= 4.2, <= 6.0)
```

**Comment by alecdotninja** [comment]
@rexmadden Thank you for reporting this issue. It should now be fixed in [0.1.7](https://rubygems.org/gems/active_record_distinct_on/versions/0.1.7).
