### ISSUE TITLE
Support for Rails 7.0

### ISSUE THREAD

**Issue by josh-long-raylo** [alecdotninja/active_record_distinct_on#16]
_active_record_distinct_on_ currently doesn't work with [Active Record 7.0.0](https://rubygems.org/gems/activerecord/versions/7.0.0) used by Rails 7.0.

https://github.com/alecdotninja/active_record_distinct_on/blob/master/active_record_distinct_on.gemspec#L20
`spec.add_dependency 'activerecord', '>= 5.2', '< 6.2'`

**Comment by alecdotninja** [comment]
Thanks to @yosiat's work in #17, this should now be fixed in [`v1.3.0`](https://rubygems.org/gems/active_record_distinct_on/versions/1.3.0). :tada:
