### ISSUE TITLE
distinct_on doesn't work  within has_many scope

### ISSUE THREAD

**Issue by Hampei** [alecdotninja/active_record_distinct_on#18]
Using  distinct_on  within a has_many scope, does not throw an  error, but seems to be completely ignored.

```
has_many :leaves, -> { distinct_on(:id) }, through: :branches
```

```
>  tree.leaves.to_sql
=> "select leaves.* from leaves inner join ..."

> tree.leaves.distinct_on(:id).to_sql
=> "select  distinct  on (leaves.id) leaves.*  from leaves inner join ..."
```

What  is  needed is that `ActiveRecord::Relation::Merger::NORMAL_VALUES` needs distinct_on added as well, 
but for that to work `distinct_on!` needs  to  save  the  given input without  the mapping to  arel attributes, since  that will happen multiple  times  then. The mapping should be moved  to the `build_distinct_on`.

**Comment by alecdotninja** [comment]
Thank you for your work on this, @Hampei !

The fix for this issue has been released in [version 1.4.0](https://rubygems.org/gems/active_record_distinct_on/versions/1.4.0). :tada:
