### ISSUE TITLE
Support for Rails 5.2.1

### ISSUE THREAD

**Issue by rexmadden** [alecdotninja/active_record_distinct_on#6]
I'm trying to upgrade to 5.2.1. Right now it requires 5.2

    active_record_distinct_on (>= 0.1.4) was resolved to 0.1.4, which depends on
      activerecord (<= 5.2, >= 4.2)

**Comment by alecdotninja** [comment]
@rexmadden Thank you for the bug report. This issue should now be fixed in [`0.1.5`](https://rubygems.org/gems/active_record_distinct_on/versions/0.1.5).
